# Catthode
# Theme create by: https://github.com/catthode
# Update by(sort by time):

code_syntax_highlight = "catthode"

# ======== Border ========
file_panel_border = "#636363"
sidebar_border = "#d9b98c"
footer_border = "#ff9e3b"

# ======== Border Active ========
file_panel_border_active = "#e8e8e8"
sidebar_border_active = "#fae2c8"
footer_border_active = "#ff9e3b"
modal_border_active = "#fae2c8"

# ======== Background (bg) ========
full_screen_bg = "#000000"
file_panel_bg = "#000000"
sidebar_bg = "#000000"
footer_bg = "#141414"
modal_bg = "#141414"

# ======== Foreground (fg) ========
full_screen_fg = "#ffffff"
file_panel_fg = "#ffffff"
sidebar_fg = "#ffffff"
footer_fg = "#ffffff"
modal_fg = "#ffffff"

# ======== Special Color ========
cursor = "#ff9e3b"
correct = "#b9d665"
error = "#ff6b6b"
hint = "#aee6d6"
cancel = "#b3b3b3"

# Gradient color can only have two color!
gradient_color = ["#ff6b6b", "#ffb86c"]

# ======== File Panel Special Items ========
file_panel_top_directory_icon = "#ff9e3b"
file_panel_top_path = "#ffb86c"
file_panel_item_selected_fg = "#ff9e3b"
file_panel_item_selected_bg = "#2d2d2d"

# ======== Sidebar Special Items ========
sidebar_title = "#ffb86c"
sidebar_item_selected_fg = "#ff9e3b"
sidebar_item_selected_bg = "#2d2d2d"
sidebar_divider = "#757575"

# ======== Modal Special Items ========
modal_cancel_fg = "#e8e8e8"
modal_cancel_bg = "#636363"
modal_confirm_fg = "#000000"
modal_confirm_bg = "#ff9e3b"

# ======== Help Menu ========
help_menu_hotkey = "#f08d49"
help_menu_title = "#ffb86c"
